// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Rp8fp79kiToRK8LMDCfpfqfFmhTl-tc',
    appId: '1:496031648674:web:a3806a8211424e070800fb',
    messagingSenderId: '496031648674',
    projectId: 'test-nextera',
    authDomain: 'test-nextera.firebaseapp.com',
    storageBucket: 'test-nextera.firebasestorage.app',
    measurementId: 'G-65F1VK9XZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCotoOEjpXsJWnaPR_qW1SguUbE751splI',
    appId: '1:496031648674:android:d6b8b8acec29afee0800fb',
    messagingSenderId: '496031648674',
    projectId: 'test-nextera',
    storageBucket: 'test-nextera.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wL4AMYNykBi1hsZKLVJzszsy39M1q3c',
    appId: '1:496031648674:ios:9309f4c0348bea5c0800fb',
    messagingSenderId: '496031648674',
    projectId: 'test-nextera',
    storageBucket: 'test-nextera.firebasestorage.app',
    iosBundleId: 'com.nexteragroup.salesbetting.salesbetting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1wL4AMYNykBi1hsZKLVJzszsy39M1q3c',
    appId: '1:496031648674:ios:9309f4c0348bea5c0800fb',
    messagingSenderId: '496031648674',
    projectId: 'test-nextera',
    storageBucket: 'test-nextera.firebasestorage.app',
    iosBundleId: 'com.nexteragroup.salesbetting.salesbetting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Rp8fp79kiToRK8LMDCfpfqfFmhTl-tc',
    appId: '1:496031648674:web:48b62b011874c0870800fb',
    messagingSenderId: '496031648674',
    projectId: 'test-nextera',
    authDomain: 'test-nextera.firebaseapp.com',
    storageBucket: 'test-nextera.firebasestorage.app',
    measurementId: 'G-41EHCFPPL4',
  );
}
